version: "3.9"
name: "w2g-builder-services"
services:
  rabbitmq:
    image: rabbitmq
    container_name: w2g-builder-rabbitmq-1
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-volume/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 15
  messenger-postgres:
    container_name: messenger-postgres-1
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: messenger-db
    volumes:
      - ./docker-volume/messenger-postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 1s
      timeout: 3s
      retries: 3
  messenger-redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  messenger-app:
    build:
      context: ./apps/messenger
      dockerfile: Dockerfile
    depends_on:
      messenger-redis:
        condition: service_healthy
      messenger-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./apps/messenger/.env
    environment:
      - APP_PORT=3000
      - RABBITMQ_HOST=host.docker.internal
      - DATABASE_HOST=host.docker.internal
      - REDIS_HOST=host.docker.internal
    ports:
      - "3000:3000"
