package dev.felipeflohr.w2gservices.builder.repositories

import dev.felipeflohr.w2gservices.builder.entities.DiscordDelimitationMessageEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface DiscordDelimitationMessageRepository : JpaRepository<DiscordDelimitationMessageEntity, Long>, DiscordDelimitationMessageCustomRepository
