CREATE SEQUENCE IF NOT EXISTS "DISCORD_DELIMITATION_MESSAGE_PK" START WITH 1 INCREMENT BY 50;

CREATE TABLE "TB_DISCORD_DELIMITATION_MESSAGE"
(
    "DDM_ID"     BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "VERSION"    BIGINT,
    "DDM_DMEID"  BIGINT NOT NULL,
    CONSTRAINT "PK_TB_DISCORD_DELIMITATION_MESSAGE" PRIMARY KEY ("DDM_ID")
);

ALTER TABLE "TB_DISCORD_DELIMITATION_MESSAGE"
    ADD CONSTRAINT "UC_TB_DISCORD_DELIMITATION_MESSAGE_DDM_DMEID" UNIQUE ("DDM_DMEID");

ALTER TABLE "TB_DISCORD_DELIMITATION_MESSAGE"
    ADD CONSTRAINT FK_TB_DISCORD_DELIMITATION_MESSAGE_ON_DDM_DMEID FOREIGN KEY ("DDM_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID");