------
-- Creates the file reference table
------
CREATE SEQUENCE IF NOT EXISTS "MESSAGE_FILE_PK" START WITH 1 INCREMENT BY 50;

CREATE TABLE "TB_MESSAGE_FILE_REFERENCE"
(
    "MFR_ID"     BIGINT        NOT NULL,
    "CREATED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "UPDATED_AT" TIMESTAMP WITHOUT TIME ZONE,
    "VERSION"    BIGINT,
    "MFR_DMEID"  BIGINT        NOT NULL,
    "MFR_URL"    VARCHAR(2048) NOT NULL,
    "MFR_HASH"   VARCHAR(64)   NOT NULL,
    CONSTRAINT PK_TB_MESSAGE_FILE_REFERENCE PRIMARY KEY ("MFR_ID")
);

ALTER TABLE "TB_MESSAGE_FILE_REFERENCE"
    ADD CONSTRAINT "UC_TB_MESSAGE_FILE_REFERENCE_MFR_URL" UNIQUE ("MFR_URL");

ALTER TABLE "TB_MESSAGE_FILE_REFERENCE"
    ADD CONSTRAINT "FK_TB_MESSAGE_FILE_REFERENCE_ON_MFR_DMEID" FOREIGN KEY ("MFR_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID");

-------
-- Creates the file reference log table
-------
CREATE SEQUENCE IF NOT EXISTS "MESSAGE_FILE_LOG_PK" START WITH 1 INCREMENT BY 50;

CREATE TABLE "TB_MESSAGE_FILE_LOG"
(
    "MFL_ID"          BIGINT   NOT NULL,
    "CREATED_AT"      TIMESTAMP WITHOUT TIME ZONE,
    "UPDATED_AT"      TIMESTAMP WITHOUT TIME ZONE,
    "VERSION"         BIGINT,
    "MFL_DMEID"       BIGINT   NOT NULL,
    "MFL_HTTP_STATUS" SMALLINT NOT NULL,
    "MFL_BODY"        TEXT     NOT NULL,
    CONSTRAINT PK_TB_MESSAGE_FILE_LOG PRIMARY KEY ("MFL_ID")
);

ALTER TABLE "TB_MESSAGE_FILE_LOG"
    ADD CONSTRAINT "FK_TB_MESSAGE_FILE_LOG_ON_MFL_DMEID" FOREIGN KEY ("MFL_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID");