-- Update foreign key constraint for TB_DISCORD_DELIMITATION_MESSAGE
ALTER TABLE "TB_DISCORD_DELIMITATION_MESSAGE" DROP CONSTRAINT FK_TB_DISCORD_DELIMITATION_MESSAGE_ON_DDM_DMEID;
ALTER TABLE "TB_DISCORD_DELIMITATION_MESSAGE"
    ADD CONSTRAINT FK_TB_DISCORD_DELIMITATION_MESSAGE_ON_DDM_DMEID FOREIGN KEY ("DDM_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID") ON DELETE CASCADE;

-- Update foreign key constraint for TB_MESSAGE_FILE_REFERENCE
ALTER TABLE "TB_MESSAGE_FILE_REFERENCE" DROP CONSTRAINT "FK_TB_MESSAGE_FILE_REFERENCE_ON_MFR_DMEID";
ALTER TABLE "TB_MESSAGE_FILE_REFERENCE"
    ADD CONSTRAINT "FK_TB_MESSAGE_FILE_REFERENCE_ON_MFR_DMEID" FOREIGN KEY ("MFR_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID") ON DELETE CASCADE;

-- Update foreign key constraint for TB_MESSAGE_FILE_LOG
ALTER TABLE "TB_MESSAGE_FILE_LOG" DROP CONSTRAINT "FK_TB_MESSAGE_FILE_LOG_ON_MFL_DMEID";
ALTER TABLE "TB_MESSAGE_FILE_LOG"
    ADD CONSTRAINT "FK_TB_MESSAGE_FILE_LOG_ON_MFL_DMEID" FOREIGN KEY ("MFL_DMEID") REFERENCES "TB_DISCORD_MESSAGE" ("DME_ID") ON DELETE CASCADE;
