ALTER TABLE "TB_DISCORD_DELIMITATION_MESSAGE" ALTER COLUMN "DDM_ID" SET DEFAULT nextval('"DISCORD_DELIMITATION_MESSAGE_PK"');
ALTER TABLE "TB_DISCORD_MESSAGE" ALTER COLUMN "DME_ID" SET DEFAULT nextval('"DISCORD_MESSAGE_PK"');
ALTER TABLE "TB_DISCORD_MESSAGE_AUTHOR" ALTER COLUMN "DMA_ID" SET DEFAULT nextval('"DISCORD_MESSAGE_AUTHOR_PK"');
ALTER TABLE "TB_MESSAGE_FILE_LOG" ALTER COLUMN "MFL_ID" SET DEFAULT nextval('"MESSAGE_FILE_LOG_PK"');
ALTER TABLE "TB_MESSAGE_FILE_REFERENCE" ALTER COLUMN "MFR_ID" SET DEFAULT nextval('"MESSAGE_FILE_PK"');
